feat(pasos-activación): pasos pandemia
andes/andes.github.io pull request #1
Opened 2021-04-07 19:10 UTC by andrrrl

2021-04-09 11:14 UTC, JSantarelli reviewed
Quizás aclarar que debe enviar imágen del dni en el primer paso (entre otros datos)? Más que nada por que el paso dos comienza... 'una vez validada tu identidad...'

2021-04-09 16:52 UTC, andrrrl commented
> Quizás aclarar que debe enviar imágen del dni en el primer paso (entre otros datos)? Más que nada por que el paso dos comienza... 'una vez validada tu identidad...'

Si, es cierto. En este caso lo obvié porque cuando ingresás a la app, la misma te pide todos esos datos (imagen, etc). Veo de poner un texto que ayude a prefigurar eso.

2021-04-09 17:17 UTC, juuliotero requested changes
![image](https://user-images.githubusercontent.com/7090371/114217257-4f285f00-993e-11eb-85ec-fd945d2db239.png)

Creo que no debería ir el botón de 'Ver puntos de acreditación' si va a ser todo por mail

2021-04-13 11:40 UTC, juuliotero approved these changes

2021-04-14 18:18 UTC, JSantarelli approved these changes

2021-04-21 11:16 UTC, merged