fix: typo
andes/andes.github.io pull request #3
Opened 2021-05-26 16:46 UTC by andrrrl

2021-06-03 11:05 UTC, JSantarelli requested changes

2021-06-03 11:05 UTC, JSantarelli commented on _includes/registro.html
> +                <p>5) Ya podemos empezar a utilizar la aplicación.</p>
@andrrrl en todo texto se viene hablando en segunda persona singular y en ésta línea cambia al plural de la primera persona.

2021-06-03 12:24 UTC, andrrrl commented on _includes/registro.html
> +                <p>5) Ya podemos empezar a utilizar la aplicación.</p>
Ups se me pasó ese! gracias!

2021-06-16 15:55 UTC, kroce approved these changes

2021-06-16 15:56 UTC, JSantarelli approved these changes

2021-06-16 15:56 UTC, merged